### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by prosanelli** [ivantsepp/codeclimate-scss-lint#2]
I ran scss-lint in codeclimate cli and here is my output. I ran the gem version of scss-lint and it works.

```
$ codeclimate analyze
error: (CC::Analyzer::Engine::EngineFailure) engine scss-lint failed with status 1 and stderr
/usr/src/app/lib/scss_lint/reporters/codeclimate_reporter.rb:8:in `block in report_lints': undefined method `name' for nil:NilClass (NoMethodError)
    from /usr/src/app/lib/scss_lint/reporters/codeclimate_reporter.rb:5:in `map'
    from /usr/src/app/lib/scss_lint/reporters/codeclimate_reporter.rb:5:in `report_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:165:in `block in report_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:164:in `each'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:164:in `report_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:59:in `scan_for_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:51:in `act_on_options'
    from /usr/src/app/lib/cc/engine/scss-lint.rb:19:in `block in run'
    from /usr/src/app/lib/cc/engine/scss-lint.rb:17:in `chdir'
    from /usr/src/app/lib/cc/engine/scss-lint.rb:17:in `run'
    from /usr/src/app/bin/codeclimate-scss-lint:9:in `<main>'
Starting analysis
```

**Comment by ivantsepp** [comment]
I believe I was able to reproduce your error. I wanted to double check what output you had when you ran the gem version of scss-lint. Did you have syntax error warnings or file encoding warnings?

**Comment by mrb** [comment]
@prosanelli Sorry about that! What code were you analyzing?

**Comment by prosanelli** [comment]
@ivantsepp was correct:

```
Syntax Error: Invalid CSS after "...h_properties %>": expected "{", was "}"
```

We had a file with the extensions *.css.scss that should have been *.scss.erb. so fixing the file extension worked. thanks

**Comment by prosanelli** [comment]
@mrb I was analyzing a private repo.

**Comment by mrb** [comment]
@prosanelli Thanks! @ivantsepp Will try to roll out this new version ASAP.

**Comment by mrb** [comment]
@prosanelli If you want to run this new version locally to test it, you can `docker build -t codeclimate/codeclimate/codeclimate-scss-lint .` in this directory, and then run `codeclimate analyze --dev` in your private repo.

**Comment by prosanelli** [comment]
My cc analysis is still failing (with the scss file that is actually an erb). Here are my steps:

```
~/Code/codeclimate-scss-lint$ docker build -t codeclimate/codeclimate/codeclimate-scss-lint .
Sending build context to Docker daemon 76.29 kB
Step 0 : FROM codeclimate/alpine-ruby:b38
 ---> fc6c8b5e5306
Step 1 : WORKDIR /usr/src/app
 ---> Using cache
 ---> d43a3cb89934
Step 2 : COPY Gemfile /usr/src/app/
 ---> Using cache
 ---> 4d2ece3bdbf5
Step 3 : COPY Gemfile.lock /usr/src/app/
 ---> Using cache
 ---> 6af16f7b023f
Step 4 : RUN apk --update add ruby ruby-dev ruby-bundler build-base &&     bundle install -j 4 --without test development &&     apk del build-base && rm -fr /usr/share/ri
 ---> Using cache
 ---> 7257668b6076
Step 5 : RUN adduser -u 9000 -D app
 ---> Using cache
 ---> 06877f24a20d
Step 6 : USER app
 ---> Using cache
 ---> 17359cea7cc9
Step 7 : COPY . /usr/src/app
 ---> Using cache
 ---> 07b01b3f26fe
Step 8 : CMD /usr/src/app/bin/codeclimate-scss-lint
 ---> Using cache
 ---> b78bff8e6136
Successfully built b78bff8e6136
```

then

```
~/Code/my_repo$ codeclimate analyze --dev
Starting analysis
Running scss-lint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine scss-lint failed with status 1 and stderr
/usr/src/app/lib/scss_lint/reporters/codeclimate_reporter.rb:8:in `block in report_lints': undefined method `name' for nil:NilClass (NoMethodError)
    from /usr/src/app/lib/scss_lint/reporters/codeclimate_reporter.rb:5:in `map'
    from /usr/src/app/lib/scss_lint/reporters/codeclimate_reporter.rb:5:in `report_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:165:in `block in report_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:164:in `each'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:164:in `report_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:59:in `scan_for_lints'
    from /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:51:in `act_on_options'
    from /usr/src/app/lib/cc/engine/scss-lint.rb:19:in `block in run'
    from /usr/src/app/lib/cc/engine/scss-lint.rb:17:in `chdir'
    from /usr/src/app/lib/cc/engine/scss-lint.rb:17:in `run'
    from /usr/src/app/bin/codeclimate-scss-lint:9:in `<main>'
```

**Comment by ivantsepp** [comment]
Hmm weird, I tried the steps and it worked for me. Looking at your output, I see `docker build -t codeclimate/codeclimate/codeclimate-scss-lint .`. Should it be `docker build -t codeclimate/codeclimate-scss-lint .` instead?

**Comment by mrb** [comment]
@prosanelli @ivantsepp D'oh! `docker build -t codeclimate/codeclimate-scss-lint .`

**Comment by prosanelli** [comment]
ok that worked! thanks.

**Comment by mrb** [comment]
@prosanelli :+1:
